pub mod add_profile;
pub mod add_profile_transaction_condition;
pub mod view_profile;
pub mod fetch_ipfs_profile;
pub mod view_profile_address;
pub mod view_profiles;
pub mod last_citizen_id;
pub mod profile_paginate;
pub mod fetch_storage_profile;